from enum import StrEnum

from pydantic import BaseModel


class ErrorCode(StrEnum):
    INCORRECT_CREDENTIALS = "INCORRECT_CREDENTIALS"
    INSUFFICIENT_PRIVILEGES = "INSUFFICIENT_PRIVILEGES"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    NOT_FOUND = "NOT_FOUND"

    USERNAME_ALREADY_TAKEN = "USERNAME_ALREADY_TAKEN"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class Error(BaseModel):
    error_code: ErrorCode
    user_feedback: str
